#!/bin/sh
set -e
cat <<EOH >/config/openvpn/credentials
$PIA_USERNAME
$PIA_PASSWORD
EOH

test -d /data || mkdir -v /data
test -d /dev/net || mkdir -vp /dev/net
test -c /dev/net/tun || mknod /dev/net/tun c 10 200
openvpn --mktun --dev $VPN_DEV

/usr/local/bin/sigil -p -f /config/openvpn/openvpn.tmpl >/config/openvpn/openvpn.ovpn
rm -f /config/openvpn/openvpn.tmpl
exec /usr/bin/supervisord -c /config/supervisor.conf
